#+BEGIN_COMMENT
.. title: Translating R to python
.. slug: translating-r-to-python
.. date: 2017-08-27 15:52:28 UTC-05:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT


* Background

I've been using =R= for at least [[https://stackoverflow.com/questions/9057006/getting-strings-recognized-as-variable-names-in-r][5 years]]. Lately, I've been trying to pick up =python= as
well, which is quite the learning experience! I've been through some tutorials (or pieces
of them) from [[http://greenteapress.com/thinkpython/html/index.html][/think python/]] and [[https://learnpythonthehardway.org/][lpthw]], as well as [[https://www.coursera.org/learn/python][classes on Coursera]]. With some basics
under my belt, I started getting into =numpy= and =pandas=, which is where things got
tricky. I can vaguely recall a time in my =R= Padawan days when I had a sense of what I
wanted to do, but didn't know enough to even formulate the question correctly. I also find
I don't learn well by just reading docs. I want to poke and prod around, trying to wrap my
head around what I'm reading. For example, I ran across the the function =tolist()= via
[[https://stackoverflow.com/questions/34898159/python-pandas-series-combine-the-rows][SO]], but have no idea how to interpret [[https://pandas.pydata.org/pandas-docs/stable/generated/pandas.Series.tolist.html][this]] as it is:

#+begin_example
Series.tolist()
  Convert Series to a nested list
#+end_example

I thought a =pd.Series= was just like an =R= vector; why would it be "nestable" in the
first place? What is a nested list and why do I want that? Some [[https://stackoverflow.com/questions/23748995/pandas-dataframe-to-list][examples]] just show that it
converts from a =pd.Series= to a list. I don't see any "nesting," but then don't know what
that is.

In any case, the point is that instead of trying to just learn =pandas= in some linear
way, I thought it might be more effective to simply take some =R= code and translate it to
=python=. I know what I want to know and the tools I would use in =R=, so getting my brain
around how to do the same in =python= seemed like an interesting way to learn. Whatever I
pickup will be relevant (I'm already doing these sorts of tasks), and the learning is more
targetted (I'm extracting the small % of information I need vs. trying to digest things I
likely will never use).

* The challenge

The data consists of some raw test data from a sensor. I've anonymized what it is, but the
gist is as follows:

- I start logging data via USB at 1000 Hz
- The test begins and I get the data of interest
- I stop logging that sample

Because the logging software and machine don't communicate, I end up with varying amounts
of baseline, nominally zero data before the test occurs. Once it's over, I have a "tail"
of unknown length after the test is complete. I tend to have anywhere between 5-25 tests,
and I want to align their starts for plotting/analysis. I've created a sample dataset [[../files/r-to-python-data.csv][here]]
if you want to follow along.

* Using R

So you can get a sense of how I'm doing this in =R= (comments/improvements welcome!),
let's look at the raw data:

#+begin_src R :session r :exports code :results silent

library(ggplot2)
library(reshape2)

data <- read.csv("r-to-python-data.csv")

#+end_SRC



 
